---
# Create NameSpace ladit
apiVersion: v1
kind: Namespace
metadata:
  name: ladit

---
# Deployment for the PostgreSQL container
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: ladit
  labels:
    app: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-db
        tier: postgreSQL
    spec:
      containers:
      - name: postgresql
        image: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-db-credentials
                key: user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-db-credentials
                key: password
          - name: POSTGRES_DB
            value: 'postgres'
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgresql-volume-mount
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - name: postgresql-volume-mount
          persistentVolumeClaim:
            claimName: postgres-pv-claim

---
# Service for PostgreSQL container
apiVersion: v1
kind: Service
metadata:
  name: db-postgres-service
  namespace: ladit
spec:
  selector:
    app: postgres-db
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432

---
# Secrets for the DataBase credential ManagementS
apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-credentials
  namespace: ladit
type: Opaque
data:
  user: cG9zdGdyZXM=
  password: cG9zdGdyZXM=

---
# PersistentVolumeClaim for the db deployment
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ladit
  name: postgres-pv-claim
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
